version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python generator.py powershell_attack.txt
  post_build:
    commands:
      - echo Build completed on `date`
